[package]
name = "total"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.2.5", features = ["derive"] }
which = "4.0.2"
winreg = "0.7"
dialoguer = "0.9"
